### ISSUE TITLE
how to generate 3d mesh from the outputs of evaluate.py file

### ISSUE THREAD

**Issue by ajithvcoder** [cgarg-tud/GeomAwareLoss#2]
Hi @cgarg-tud ,

could you tell how to generate 3d mesh from the outputs of evaluate.py file . parse.py file was written for 3d mesh generation of scannet images. i wanted to know for a single rgb image method . 
![snap_results](https://user-images.githubusercontent.com/8075112/97103279-74e3e380-16d1-11eb-9dbd-1c4039d086b9.PNG)
 
you can refer below issue also

https://github.com/NVlabs/planercnn/issues/53

**Comment by cgarg-tud** [comment]
hi @ajithvallabai. First select the model type you want for rendering : (normals, rgb, semantics, ground truth, superpixel improved) here and then provide the parameters to the steps involved in each type of model.

https://github.com/cgarg-tud/GeomAwareLoss/blob/d5f1de6f7be833452550f2dbe2c14c17fb8c4bc2/evaluate.py#L926
